public enum EventType
{
    //FSM
    FSM_NEXT_STEP,
    FSM_FAIL_STEP,
    FSM_FINISH,

    //RESOURCES CHANGE
    TOOL_CHANGE,
    WOOD_CHANGE,
    FOOD_CHANGE,
    STAMINA_CHANGE,

    //SPENT RESOURCES
    WOOD_SPENT,
    FOOD_SPENT,
    STAMINA_SPENT,

    //PARTICLES
    SLEEP_PARTICLE_PLAY,
    SLEEP_PARTICLE_STOP,

    FARM_PARTICLE_PLAY,
    FARM_PARTICLE_STOP,
    
    HUNT_PARTICLE_PLAY,
    HUNT_PARTICLE_STOP,

    CHOP_PARTICLE_PLAY,
    CHOP_PARTICLE_STOP,

    BUILD_PARTICLE_PLAY,
    BUILD_PARTICLE_STOP,
}
